name: Flask CI/CD to Render

on:
  push:
    branches:
      - main   # Deploy on push to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Cache pip dependencies for faster subsequent builds
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests
      # - name: Run tests
      #   run: |
      #     pytest

      # Notify deployment handled by Render's GitHub integration
      - name: Deployment
        run: echo "Render automatically deploys from GitHub on push to main"
